### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/NRCDict.json'

### ISSUE THREAD

**Issue by xhc19930714** [zhouzhouyang520/IAMM#1]
I am very interest of your work, so I want to learn from you code.   I followed the instruction and ran the command, it raised the error "FileNotFoundError: [Errno 2] No such file or directory: 'data/NRCDict.json'", I also download your data and put it in the right place. I check the folder but don't find the corresponding file. Did you change the name of that file? 

![2024-06-17_003143](https://github.com/zhouzhouyang520/IAMM/assets/17611259/41444aa8-6988-4b26-a24c-8ce1697a7fea)

**Comment by zhouzhouyang520** [comment]
I'm very sorry for this issue. The problem occurred because I lost the file during the upload process. I have now re-uploaded it successfully. You can download the file from here and place it in the data folder: https://github.com/zhouzhouyang520/IAMM/tree/main/data
