### ISSUE TITLE
Test results and assessment questions

### ISSUE THREAD

**Issue by yanlong1211** [zhouzhouyang520/IAMM#2]
Dear Author
I am in the process of reproducing my paper and the results obtained from model testing as well as model evaluation are quite different from the results in your paper.

I look forward to your response and hope to have the opportunity to learn more from your work.

**Comment by zhouzhouyang520** [comment]
Hello, to facilitate model replication, we've created a new branch containing our trained model. You can use this to reproduce the paper's results. Instructions:

1.Switch to the IAMM_bak branch and download the code.
2.Download the trained model ( [Baidu cloud link](https://pan.baidu.com/s/18_l956vgtLmk_w1WG783Jg?pwd=pm7b) with Code: pm7b or [Google cloud link](https://drive.google.com/file/d/1nQZoygdUmCTqxuoyzc39ELe0Qxu38lzn/view?usp=drive_link)) and place it in the save/test/ folder.
3.Run the code: sh run.sh

If you plan to train the model yourself, note these factors affecting performance:

1.Environmental differences: Our model achieved 55.9 Acc on Tesla T4 GPU, but may be -2 points lower on GeForce RTX 3090.
2.Iteration numbers: We used 14,399 iterations, which yielded good results.
3.Parameter settings: Carefully check all parameters as they significantly impact the model.
