### ISSUE TITLE
Test results and assessment anomalies

### ISSUE THREAD

**Issue by yanlong1211** [zhouzhouyang520/IAMM#3]
Dear Author
First of all, thank you for providing me the new branch of the trained model. After that I tried to train the model on the basis of consistent parameters, the cross-validation results were more normal, and I stopped iterating after 17599 iterations. However, in the testing and evaluation phase of the model, the results are abnormal, the PPL metrics reached more than 8000, the ACC metrics are only 2%, and the Dist-1 and Dist-2 metrics are also much different, so I would like to ask you what is the reason for this, and I hope that you can give me some suggestions.

I look forward to your response and hope to have the opportunity to learn more from your work.

**Comment by zhouzhouyang520** [comment]
Hello, here are my some suggestions:

When testing, select the model you want to test, not 'IAMM_19_9496.3010_0.0268' (which is a model after 19 iterations, used only for testing).
If performance doesn't improve after adjusting model parameters, debug by checking:
a) Is the train/validation/test data split 8:1:1?
b) Is the input data format correct?
c) Is the iteration numbers of the model too high or too low?
d) Do other models (e.g., CEM) show similar issues?

Based on the abnormal PPL and Acc metrics, I suspect the model may be unconverged or overfitted.

**Comment by zhouzhouyang520** [comment]
> Dear Author First of all, thank you for providing me the new branch of the trained model. After that I tried to train the model on the basis of consistent parameters, the cross-validation results were more normal, and I stopped iterating after 17599 iterations. However, in the testing and evaluation phase of the model, the results are abnormal, the PPL metrics reached more than 8000, the ACC metrics are only 2%, and the Dist-1 and Dist-2 metrics are also much different, so I would like to ask you what is the reason for this, and I hope that you can give me some suggestions.
> 
> I look forward to your response and hope to have the opportunity to learn more from your work.

Hello, here are my some suggestions:

When testing, select the model you want to test, not 'IAMM_19_9496.3010_0.0268' (which is a model after 19 iterations, used only for testing).
If performance doesn't improve after adjusting model parameters, debug by checking:
a) Is the train/validation/test data split 8:1:1?
b) Is the input data format correct?
c) Is the iteration numbers of the model too high or too low?
d) Do other models (e.g., CEM) show similar issues?

Based on the abnormal PPL and Acc metrics, I suspect the model may be unconverged or overfitted.
